/** Alle deutschen Oberflächentexte an einer Stelle. */
export const de = {
  title: 'Logistikum',
  subtitle: 'Logistik-Campus-Manager',
  noWebgl: 'Dein Browser kann leider keine 3D-Grafik (WebGL) anzeigen.',
  common: { ok: 'OK', cancel: 'Abbrechen', close: 'Schließen' },
  menu: {
    newGame: 'Neues Spiel',
    load: 'Laden',
    settings: 'Einstellungen',
    download: 'Download (ZIP)',
    downloadHint: 'Spielbare Version zum Entpacken und Doppelklicken',
  },
  pause: {
    title: 'Spiel pausiert',
    resume: 'Weiterspielen',
    save: 'Speichern',
    load: 'Laden',
    settings: 'Einstellungen',
    mainMenu: 'Hauptmenü',
    leaveTitle: 'Zum Hauptmenü?',
    leaveMessage: 'Nicht gespeicherter Fortschritt geht verloren.',
    leaveConfirm: 'Zum Hauptmenü',
  },
  hud: {
    pause: 'Pause',
    paused: 'PAUSE',
    menu: 'Menü',
    speed: (s: number): string => `${s}x`,
    speedTitle: (s: number, key: number): string => `Geschwindigkeit ${s}x (Taste ${key})`,
    pauseTitle: 'Pause / Weiter (Leertaste)',
    menuTitle: 'Menü (Esc)',
    purchase: 'Einkauf',
    balanceTitle: 'Kontostand · Klick öffnet die Kasse',
    weekdays: ['So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa'],
  },
  settings: {
    title: 'Einstellungen',
    autosave: 'Autosave-Intervall',
    autosaveOption: (m: number): string => `alle ${m} Minuten`,
    cameraSensitivity: 'Kamera-Empfindlichkeit',
    edgeScroll: 'Karte am Bildschirmrand verschieben',
    saved: 'Einstellungen gespeichert',
  },
  save: {
    saveTitle: 'Spielstand speichern',
    loadTitle: 'Spielstand laden',
    nameLabel: 'Name des Spielstands',
    defaultName: (date: string): string => `Campus ${date}`,
    saveButton: 'Speichern',
    overwriteHint: 'Oder einen vorhandenen Spielstand überschreiben:',
    overwriteTitle: 'Spielstand überschreiben?',
    overwriteMessage: (name: string): string => `„${name}“ wird durch den aktuellen Stand ersetzt.`,
    overwriteConfirm: 'Überschreiben',
    slots: 'Speicherplätze',
    backups: 'Automatische Sicherungen',
    empty: 'Noch keine Spielstände.',
    emptyBackups: 'Noch keine automatischen Sicherungen.',
    load: 'Laden',
    delete: 'Löschen',
    deleteTitle: 'Spielstand löschen?',
    deleteMessage: (name: string): string => `„${name}“ wird endgültig gelöscht.`,
    deleteConfirm: 'Löschen',
    loadInGameTitle: 'Spielstand laden?',
    loadInGameMessage: 'Nicht gespeicherter Fortschritt des laufenden Spiels geht verloren.',
    savedAt: (when: string): string => `gespeichert ${when}`,
    autosaveName: 'Automatische Sicherung',
    export: 'Als Datei exportieren',
    import: 'Datei importieren …',
    saved: 'Gespeichert',
    loaded: 'Spielstand geladen',
    exported: 'Datei exportiert',
    autosaved: 'Automatisch gespeichert',
    autosaveFailed: 'Automatisches Speichern fehlgeschlagen',
    saveFailed: 'Speichern fehlgeschlagen. Der vorherige Spielstand ist unverändert.',
    errorTitle: 'Spielstand kann nicht geladen werden',
    errors: {
      notJson: 'Die Datei ist kein Spielstand (kein gültiges Format) oder wurde nicht gefunden.',
      wrongFormat: 'Die Datei ist kein Logistikum-Spielstand.',
      tooNew:
        'Der Spielstand stammt aus einer neueren Spielversion. Bitte die aktuelle Version öffnen.',
      invalidVersion: 'Die Versionsangabe im Spielstand ist beschädigt.',
      migrationFailed: 'Der Spielstand konnte nicht auf die aktuelle Version umgestellt werden.',
      invalidState: 'Der Spielstand ist beschädigt oder unvollständig.',
    },
    storageMissing:
      'Der Browser-Speicher ist nicht verfügbar. Spielstände gelten nur bis zum Schließen der Seite; bitte als Datei exportieren.',
    backupFile: {
      title: 'Sicherungsdatei',
      explain:
        'Der Autosave überschreibt zusätzlich eine Datei auf deinem Rechner. So bleibt der Stand auch erhalten, wenn der Browser-Speicher gelöscht wird.',
      unsupported:
        'Dein Browser kann keine Sicherungsdatei beschreiben (nur Chrome/Edge). Der Autosave sichert im Browser; bitte regelmäßig exportieren.',
      none: 'Noch keine Sicherungsdatei gewählt.',
      ready: (name: string): string => `Aktiv: ${name}`,
      needsPermission: (name: string): string =>
        `${name}: Zugriff muss nach dem Browser-Neustart bestätigt werden.`,
      choose: 'Sicherungsdatei wählen …',
      change: 'Andere Datei wählen …',
      reconnect: 'Zugriff erlauben',
      fileDescription: 'Logistikum-Spielstand',
      reconnectToast: 'Sicherungsdatei: Zugriff bitte bestätigen',
    },
    exportReminder: 'Denk daran, deinen Spielstand als Datei zu sichern.',
    exportNow: 'Jetzt exportieren',
  },
  build: {
    barLabel: 'Bauleiste',
    tabs: {
      roads: 'Straßen',
      zones: 'Zonen/Gebäude',
      vehicles: 'Fahrzeuge',
      demolish: 'Abriss',
    },
    truck: 'LKW kaufen',
    truckTitle: (price: string, daily: string): string =>
      `LKW kaufen (${price}, dazu ${daily} am Tag und Kilometerkosten). Er erscheint an der Einfahrt und fährt automatisch.`,
    truckBought: 'LKW gekauft, er fährt an der Einfahrt los.',
    truckNoMoney: 'Nicht genug Geld für einen LKW.',
    buildings: { testHall: 'Testhalle', exportExit: 'Export-Ausfahrt' },
    zones: { A: 'Lieferort A', B: 'Lieferort B', C: 'Lieferort C' },
    zoneItemCost: (cost: string): string => `${cost} je Feld`,
    zoneItemTitle: (name: string): string =>
      `${name} aufziehen: klicken, Rechteck ziehen, loslassen (Größe bestimmt den Lagerplatz)`,
    zoneSize: (w: number, d: number, capacity: number, cost: string): string =>
      `${w} × ${d} Felder · Lager ${capacity} je Ware · Kosten: ${cost}`,
    notConnected: 'Nicht angeschlossen: Straße an das Tor bauen',
    zoneMerges: 'wird Teil der angrenzenden Zone',
    gate: { N: 'Tor Nord', E: 'Tor Ost', S: 'Tor Süd', W: 'Tor West' },
    road: 'Straße',
    roadItemCost: (cost: string): string => `${cost} je Feld`,
    roadItemTitle: 'Straße ziehen: klicken, ziehen, loslassen (gerade oder mit einem Knick)',
    roadCost: (fields: number, cost: string): string =>
      `${fields} ${fields === 1 ? 'Feld' : 'Felder'} · Kosten: ${cost}`,
    itemTitle: (name: string, cost: string): string => `${name} bauen (${cost})`,
    cost: (cost: string): string => `Kosten: ${cost}`,
    refund: (refund: string): string => `Abreißen, Erstattung: ${refund}`,
    nothingToDemolish: 'Hier steht nichts zum Abreißen.',
    escHint: 'Esc bricht ab',
    reasons: {
      outOfBounds: 'Außerhalb des Geländes',
      occupied: 'Fläche ist belegt',
      insufficientFunds: 'Nicht genug Geld',
      unknownType: 'Unbekannter Gebäudetyp',
      tooSmall: 'Zu klein',
      notAtEdge: 'Muss am Geländerand stehen',
    },
  },
  cash: {
    title: 'Kasse',
    openTitle: 'Kasse öffnen (Einnahmen und Ausgaben)',
    balance: 'Kontostand',
    category: 'Bereich',
    today: 'Heute',
    month: 'Diesen Monat',
    income: 'Einnahmen',
    expense: 'Ausgaben',
    total: 'Summe',
    recent: 'Letzte Buchungen',
    noBookings: 'Noch keine Buchungen.',
    categories: {
      build: 'Bau',
      vehicles: 'Fahrzeuge',
      operations: 'Betrieb',
      rawGoods: 'Rohware',
      exportRevenue: 'Export-Erlös',
    },
  },
  products: { rawA: 'Rohware A', rawB: 'Rohware B', combo: 'Kombi', final: 'Endprodukt' },
  purchase: {
    title: 'Einkauf',
    openTitle: 'Rohware einkaufen (Daueraufträge und Einzelbestellungen)',
    newOrder: 'Neue Bestellung',
    product: 'Ware',
    productOption: (name: string, price: string): string => `${name} (${price} je Einheit)`,
    quantity: 'Menge je Lieferung',
    quantityOption: (n: number): string => `${n} Einheiten`,
    interval: 'Lieferung',
    intervals: {
      once: 'Einmalig',
      daily: 'Täglich',
      weekly: 'Wöchentlich',
      monthly: 'Monatlich',
    },
    total: (cost: string): string => `Kosten je Lieferung: bis zu ${cost}`,
    order: 'Bestellen',
    orders: 'Bestellungen',
    noOrders: 'Keine offenen Bestellungen.',
    line: (name: string, quantity: number, interval: string): string =>
      `${name} · ${quantity} Einheiten · ${interval}`,
    next: (when: string): string => `nächste Lieferung ${when}`,
    cancel: 'Löschen',
    hint: 'Zulieferer bringen Rohware A nach Lieferort A und Rohware B nach Lieferort B. Bezahlt wird beim Losschicken.',
    blocked: {
      noSite: 'Wartet: kein passender Lieferort gebaut',
      noRoute: 'Wartet: Lieferort nicht über die Straße erreichbar',
      full: 'Wartet: Lager voll',
      noMoney: 'Wartet: nicht genug Geld',
    },
  },
  info: {
    close: 'Infofenster schließen',
    siteName: (kind: string, n: number): string => `${kind} ${n}`,
    truckName: (n: number): string => `LKW ${n}`,
    supplier: 'Zulieferer',
    fields: (n: number): string => `${n} ${n === 1 ? 'Feld' : 'Felder'}`,
    stock: 'Lager',
    stockLine: (name: string, n: number, cap: number): string => `${name}: ${n} / ${cap}`,
    status: 'Status',
    zoneStatus: {
      working: 'Verarbeitet',
      waitingInput: 'Wartet auf Ware',
      full: 'Ausgangslager voll',
      storing: 'Lagert',
    },
    connected: 'An die Straße angeschlossen',
    gate: 'Tor',
    gateTitle: (side: string): string => `${side}: Tor auf diese Seite legen`,
    exitAccepts: (list: string): string => `Kauft: ${list}`,
    exitPrice: (name: string, price: string): string => `${name} ${price}`,
    cargo: 'Ladung',
    empty: 'leer',
    cargoLine: (n: number, name: string): string => `${n} × ${name}`,
    target: 'Ziel',
    none: '–',
    truckPhase: {
      idle: 'Wartet',
      toPickup: 'Fährt zum Laden',
      loading: 'Lädt',
      toDropoff: 'Fährt zum Abladen',
      unloading: 'Lädt ab',
    },
    idleReasons: {
      noJob: 'Wartet: keine Aufgabe',
      noRoute: 'Wartet: kein Weg (Straße fehlt)',
      noDestination: 'Wartet: kein Ziel mit Platz für die Ladung',
      noTour: 'Wartet: Tour hat keine Halte',
    },
    supplierPhase: {
      toSite: 'Bringt Rohware',
      handling: 'Lädt ab',
      toExit: 'Fährt hinaus',
      noRoute: 'Wartet: kein Weg',
    },
    mode: 'Betrieb',
    modes: { auto: 'Automatik', tour: 'Feste Tour' },
    tour: 'Tour',
    noStops: 'Noch keine Halte. Ort wählen und „Halt hinzufügen“ oder Orte im Gelände anklicken.',
    stop: (n: number): string => `${n}.`,
    actions: { load: 'Laden', unload: 'Abladen' },
    addStop: 'Halt hinzufügen',
    pickStops: 'Orte anklicken',
    pickStopsActive: 'Klicken beenden',
    pickStopsHint: 'Orte im Gelände anklicken, um sie als Halt anzuhängen. Esc beendet.',
    removeStop: 'Halt entfernen',
    moveUp: 'Halt nach oben',
    current: 'aktueller Halt',
    stopRejected: {
      invalidStop: 'Dieser Halt passt nicht zum Ort.',
      tooManyStops: 'Mehr Halte gehen nicht.',
    },
    hoverHint: 'Klicken für Details',
  },
  perf: {
    line: (fps: number, simMsPerTick: number, drawCalls: number): string =>
      `${fps.toFixed(0)} Bilder/s · Simulation ${simMsPerTick.toFixed(2)} ms/Schritt · ${drawCalls} Zeichenaufrufe`,
  },
} as const;
