/** Alle deutschen Oberflächentexte an einer Stelle. */
export const de = {
  title: 'Logistikum',
  subtitle: 'Logistik-Campus-Manager',
  noWebgl: 'Dein Browser kann leider keine 3D-Grafik (WebGL) anzeigen.',
  common: { ok: 'OK', cancel: 'Abbrechen', close: 'Schließen' },
  menu: {
    newGame: 'Neues Spiel',
    load: 'Laden',
    settings: 'Einstellungen',
    download: 'Download (ZIP)',
    downloadHint: 'Spielbare Version zum Entpacken und Doppelklicken',
  },
  pause: {
    title: 'Spiel pausiert',
    resume: 'Weiterspielen',
    save: 'Speichern',
    load: 'Laden',
    settings: 'Einstellungen',
    mainMenu: 'Hauptmenü',
    leaveTitle: 'Zum Hauptmenü?',
    leaveMessage: 'Nicht gespeicherter Fortschritt geht verloren.',
    leaveConfirm: 'Zum Hauptmenü',
  },
  hud: {
    pause: 'Pause',
    paused: 'PAUSE',
    menu: 'Menü',
    speed: (s: number): string => `${s}x`,
    speedTitle: (s: number, key: number): string => `Geschwindigkeit ${s}x (Taste ${key})`,
    pauseTitle: 'Pause / Weiter (Leertaste)',
    menuTitle: 'Menü (Esc)',
    balanceTitle: 'Kontostand',
    weekdays: ['So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa'],
  },
  settings: {
    title: 'Einstellungen',
    autosave: 'Autosave-Intervall',
    autosaveOption: (m: number): string => `alle ${m} Minuten`,
    cameraSensitivity: 'Kamera-Empfindlichkeit',
    edgeScroll: 'Karte am Bildschirmrand verschieben',
    saved: 'Einstellungen gespeichert',
  },
  save: {
    saveTitle: 'Spielstand speichern',
    loadTitle: 'Spielstand laden',
    nameLabel: 'Name des Spielstands',
    defaultName: (date: string): string => `Campus ${date}`,
    saveButton: 'Speichern',
    overwriteHint: 'Oder einen vorhandenen Spielstand überschreiben:',
    overwriteTitle: 'Spielstand überschreiben?',
    overwriteMessage: (name: string): string => `„${name}“ wird durch den aktuellen Stand ersetzt.`,
    overwriteConfirm: 'Überschreiben',
    slots: 'Speicherplätze',
    backups: 'Automatische Sicherungen',
    empty: 'Noch keine Spielstände.',
    emptyBackups: 'Noch keine automatischen Sicherungen.',
    load: 'Laden',
    delete: 'Löschen',
    deleteTitle: 'Spielstand löschen?',
    deleteMessage: (name: string): string => `„${name}“ wird endgültig gelöscht.`,
    deleteConfirm: 'Löschen',
    loadInGameTitle: 'Spielstand laden?',
    loadInGameMessage: 'Nicht gespeicherter Fortschritt des laufenden Spiels geht verloren.',
    savedAt: (when: string): string => `gespeichert ${when}`,
    autosaveName: 'Automatische Sicherung',
    export: 'Als Datei exportieren',
    import: 'Datei importieren …',
    saved: 'Gespeichert',
    loaded: 'Spielstand geladen',
    exported: 'Datei exportiert',
    autosaved: 'Automatisch gespeichert',
    autosaveFailed: 'Automatisches Speichern fehlgeschlagen',
    saveFailed: 'Speichern fehlgeschlagen. Der vorherige Spielstand ist unverändert.',
    errorTitle: 'Spielstand kann nicht geladen werden',
    errors: {
      notJson: 'Die Datei ist kein Spielstand (kein gültiges Format) oder wurde nicht gefunden.',
      wrongFormat: 'Die Datei ist kein Logistikum-Spielstand.',
      tooNew:
        'Der Spielstand stammt aus einer neueren Spielversion. Bitte die aktuelle Version öffnen.',
      invalidVersion: 'Die Versionsangabe im Spielstand ist beschädigt.',
      migrationFailed: 'Der Spielstand konnte nicht auf die aktuelle Version umgestellt werden.',
      invalidState: 'Der Spielstand ist beschädigt oder unvollständig.',
    },
    storageMissing:
      'Der Browser-Speicher ist nicht verfügbar. Spielstände gelten nur bis zum Schließen der Seite; bitte als Datei exportieren.',
    backupFile: {
      title: 'Sicherungsdatei',
      explain:
        'Der Autosave überschreibt zusätzlich eine Datei auf deinem Rechner. So bleibt der Stand auch erhalten, wenn der Browser-Speicher gelöscht wird.',
      unsupported:
        'Dein Browser kann keine Sicherungsdatei beschreiben (nur Chrome/Edge). Der Autosave sichert im Browser; bitte regelmäßig exportieren.',
      none: 'Noch keine Sicherungsdatei gewählt.',
      ready: (name: string): string => `Aktiv: ${name}`,
      needsPermission: (name: string): string =>
        `${name}: Zugriff muss nach dem Browser-Neustart bestätigt werden.`,
      choose: 'Sicherungsdatei wählen …',
      change: 'Andere Datei wählen …',
      reconnect: 'Zugriff erlauben',
      fileDescription: 'Logistikum-Spielstand',
      reconnectToast: 'Sicherungsdatei: Zugriff bitte bestätigen',
    },
    exportReminder: 'Denk daran, deinen Spielstand als Datei zu sichern.',
    exportNow: 'Jetzt exportieren',
  },
  build: {
    barLabel: 'Bauleiste',
    tabs: {
      roads: 'Straßen',
      zones: 'Zonen/Gebäude',
      vehicles: 'Fahrzeuge',
      demolish: 'Abriss',
    },
    comingSoon: 'Kommt in Kürze.',
    buildings: { testHall: 'Testhalle' },
    itemTitle: (name: string, cost: string): string => `${name} bauen (${cost})`,
    cost: (cost: string): string => `Kosten: ${cost}`,
    refund: (refund: string): string => `Abreißen, Erstattung: ${refund}`,
    nothingToDemolish: 'Hier steht nichts zum Abreißen.',
    escHint: 'Esc bricht ab',
    reasons: {
      outOfBounds: 'Außerhalb des Geländes',
      occupied: 'Fläche ist belegt',
      insufficientFunds: 'Nicht genug Geld',
      unknownType: 'Unbekannter Gebäudetyp',
    },
  },
  perf: {
    line: (fps: number, simMsPerTick: number, drawCalls: number): string =>
      `${fps.toFixed(0)} Bilder/s · Simulation ${simMsPerTick.toFixed(2)} ms/Schritt · ${drawCalls} Zeichenaufrufe`,
  },
} as const;
